#server:
#  port: 9090
#  tomcat:
#    uri-encoding: UTF-8

spring:
  datasource:
    url: jdbc:mysql://39.106.148.113:3306/wangtest?characterEncoding=UTF-8
    username: wang
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    useSSL: false
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        hbm2ddl:
          auto: update
server:
    port: 8443
    session-timeout: 60
    tomcat:
      max-threads: 300
      uri-encoding: UTF-8
    ssl:
      key-store: classpath:214565831350244.pfx
      key-store-password: 214565831350244
      keyStoreType: PKCS12